CREATE TABLE TB_CLIENTE (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,

    NM_NOME VARCHAR(255) NOT NULL,
    CD_CPF VARCHAR(14) NOT NULL,
    DT_NASCIMENO DATE,

    -- Campos do objeto embutido Endereco
    NM_ENDERECO VARCHAR(255),
    NM_COMPLEMENTO VARCHAR(255),
    CD_CEP INTEGER
);